### ISSUE TITLE
Custom template not working

### ISSUE THREAD

**Issue by Adwelean** [Bluhex/october-youtube#5]
Hi,

I try to use your plugin but it work just when I use your component {% component "videos" %}, if I use a custom template the videos array contains videos in my exemple the dump() function show me 9 items but the loop not iterating .

The code in partial :

```
{{ dump(videos) }}
{# return 9 items in videos array #}
{% for video in videos %}
    {# not working #}
   {{ dump(video) }}
   <p>{{ video.title }}</p>
{% endfor %}

{# Work #}
{% component "videos" %}
```

Where is the mistake ?

**Comment by BrendonPark** [comment]
Hi, I just had a quick look into this and it might be a few issues.
1. By default the component alias is called 'latestVideos' not 'videos'  make sure you've got your name set correctly between your component declaration and tag.
2. The partial name and the alias are linked. If your component alias is 'videos' the partial should be in the path of 'videos/default.html' or else the default partial will be used.
3. The component tag shouldn't be in the component partial layout it should be in the page or partial where the component should appear.
4. Make sure you're calling `{% set videos = __SELF__.videos %}` at the beginning of your partial to make sure you're loading the videos into a local variable that can be accessed.

I checked your partial code and it is working, so that's certainly not the issue. Have a look at the things above and I'm confident that should fix your issue.

**Comment by Adwelean** [comment]
Thank for your explanation @BrendonPark, I've missed to add the component tag after the partial call :/
